///|
using @lg {
  trait AddGroup,
  trait AddMonoid,
  trait Integral,
  trait IntegralHomomorphism,
  trait MulMonoid,
  trait Nat,
  trait NatHomomorphism,
  trait One,
  trait Ring,
  trait Semiring,
  trait Zero,
}

///|
using @arithmetic {
  trait Constants,
  trait DivChecked,
  trait Exponential,
  trait Logarithmic,
  trait Sqrt,
  trait SqrtChecked,
  trait Trigonometric,
  type ArithmeticContext,
  type ArithmeticError,
}
